# This is a generated file. Not intended for manual editing.
services:
  backend:
    build:
      context: "/home/john/MRSTW/MRSTW"
      dockerfile: "MRSTW.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/MRSTW.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "mrstw.api:dev"
    ports: []
    volumes:
    - "/home/john/MRSTW/MRSTW/MRSTW.Api:/app:rw"
    - "/home/john/MRSTW/MRSTW:/src:rw"
    - "/home/john/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
